In [5]:
import torch

## Add 

In [11]:
# add two tensors
tensor_one = torch.tensor([1, 2, 3, 4, 5])
tensor_two = torch.tensor([1, 2, 3, 4, 5])
tensor_add = tensor_one + tensor_two
print (tensor_one + tensor_two)
print (tensor_one)
print (torch.add(tensor_one, tensor_two)) # torch.add(a, b) is the same as a + b
print (tensor_one.add_(tensor_two))       # In place add,  in most case don't use this.
print (tensor_one)                        # tensor_one is modified as a result

tensor([ 2,  4,  6,  8, 10])
tensor([1, 2, 3, 4, 5])
tensor([ 2,  4,  6,  8, 10])
tensor([ 2,  4,  6,  8, 10])
tensor([ 2,  4,  6,  8, 10])


## Multiply * two tensors

In [13]:
# * two tensors
tensor_one = torch.tensor([1, 2, 3, 4, 5])
print (tensor_one * tensor_two)
print (torch.mul(tensor_one, tensor_two))
print (tensor_one.mul_(tensor_two))      # in place multiplicaiton
print (tensor_one)

tensor([ 1,  4,  9, 16, 25])
tensor([ 1,  4,  9, 16, 25])
tensor([ 1,  4,  9, 16, 25])
tensor([ 1,  4,  9, 16, 25])


## Multiply by a scalar

In [ ]:
# * tensor by a scalar
tensor_mul_scalar = tensor_one * 3
tensor_mul_scalar

tensor([ 3,  6,  9, 12, 15])

## Dot Product 

In [ ]:
# Dot Product for 1d array
dot_product = torch.dot(tensor_one, tensor_two)
print (dot_product)

tensor(55)


## Matrix Multiplication

In [ ]:
tensor_one = torch.tensor([1, 2, 3, 4, 5, 6]).view(2, 3)
tensor_two = torch.tensor([1, 2, 3, 4, 5, 6]).view(3, 2)

matrix_mul = torch.matmul(tensor_one, tensor_two)
print (matrix_mul)

tensor([[22, 28],
        [49, 64]])


In [ ]:
tensor_one @ tensor_two   # same with torch.matmul

tensor([[22, 28],
        [49, 64]])