In [1]:
import torch
import numpy as np

## Create our first Tensor 

In [2]:
one_dimension = torch.tensor([1 ,2 ,3])
print (one_dimension)
print (one_dimension[2])      # return tensor value at index 2
print (one_dimension[1:])     # return tensor values from index 1 and beyond
print (one_dimension.dtype)   # print the data type of the tensor
print (one_dimension.type())  # print the type of the tensor   
print (one_dimension.size())  # print the size of the tensor

tensor([1, 2, 3])
tensor(3)
tensor([2, 3])
torch.int64
torch.LongTensor
torch.Size([3])
torch.Size([3])


## FloatTensor() vs. Tensor() vs. tensor()

torch.Tensor() is an alias for torch.FloatTensor()

In [ ]:
float_tensor = torch.FloatTensor([1, 2, 3, 4, 5])
# Be Careful: One is capitalized
Tensor = torch.Tensor([1, 2, 3, 4, 5])
tensor = torch.tensor([1, 2, 3, 4, 5])

print ("float_tensor:")
print ("data type: ",  float_tensor.dtype)
print ("tensor type: ", float_tensor.type())
print ("-------------")


print ("Tensor:")
print ("data type: ",  Tensor.dtype)
print ("tensor type: ", Tensor.type())
print ("-------------")


print ("tensor:")
print ("data type: ",  tensor.dtype)
print ("tensor type: ", tensor.type())


float_tensor:
data type:  torch.float32
tensor type:  torch.FloatTensor
-------------
Tensor:
data type:  torch.float32
tensor type:  torch.FloatTensor
-------------
tensor:
data type:  torch.int64
tensor type:  torch.LongTensor


## torch.rand() / torch.randn() / torch.randint()

torch.rand(): Returns a tensor filled with random numbers from a uniform distribution on the interval (0, 1]

torch.randn(): Returns a tensor filled with randon numbers from a normal distribution with mean 0 and variance 1 returns values between (-1, 1)

torch.randint(): Returns a tensor filled with random integers generated uniformly between low and high

In [10]:
two_by_three = torch.rand(2, 3)
two_by_three_float64 = torch.rand(3,3, dtype=torch.float64) # specify dtype
three_by_two = torch.randn(3, 2)
three_by_three = torch.randint(0, 5, (3, 3))
print (two_by_three.dtype)
print (two_by_three_float64 )
print (three_by_two)
print (three_by_three)

torch.float32
tensor([[0.0330, 0.7731, 0.4973],
        [0.7459, 0.6601, 0.9984],
        [0.9347, 0.7522, 0.9030]], dtype=torch.float64)
tensor([[-0.5543,  0.7503],
        [ 0.3874, -0.3189],
        [ 0.3220, -0.6539]])
tensor([[1, 4, 2],
        [2, 2, 3],
        [2, 1, 1]])


## View()

Views share underlying data with its base tensor. If you edit the data in the view, it will be reflected in the base tensor as well.

In [ ]:
one_row_six_column = torch.tensor([1, 2, 3, 4, 5, 6])
print (one_row_six_column)

six_row_one_column = one_row_six_column.view(6, 1)
print (six_row_one_column)

three_row_two_column = one_row_six_column.view(3, 2)
print (three_row_two_column)

tensor([1, 2, 3, 4, 5, 6])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])


## View(X, -1)
If the second argument is -1,  the value will be inferred with the size of the tensor.

In [ ]:
one_row_six_column = torch.tensor([1, 2, 3, 4, 5, 6])

three_row = one_row_six_column.view(3, -1) 
# since one_row_six_column.size() = 6 
# three_row  row number is 3, so the column number being calcuated 6/3 = 2

print (three_row)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


## Conversion between NumPy and Tensor

In [11]:
np_rabbit = np.array([1, 2, 3, 4, 5])

# Convert np array to tensor 
tensor_rabbit = torch.from_numpy(np_rabbit)

print ("type of np_rabbit: ", type(np_rabbit))
print ("type of tensor_rabbit: ", type(tensor_rabbit))

# Convert tensor to numpy
back_to_np_rabbit = tensor_rabbit.numpy()
print ("type of back_to_np_rabbit: ", type(back_to_np_rabbit))

type of np_rabbit:  <class 'numpy.ndarray'>
type of tensor_rabbit:  <class 'torch.Tensor'>
type of back_to_np_rabbit:  <class 'numpy.ndarray'>
