www.bigrabbitdata.com

## important

In [17]:
import torch
from torch import nn

## Map each unique word to an uniqe integer

In [18]:
# map each unique word to an uniqe integer
word_to_idx = {"Kanghui": 0, "is": 1, "a":2, "good":3, "girl":4}

In [19]:
# Defind the embedding. 
embeddings = nn.Embedding(5, 8)    # 5 words in vocabulary, embedding size is 8

# get the index for the work 'Kanghui'
Kanghui_index = torch.tensor(word_to_idx['Kanghui'])
embed_kanghui = embeddings(Kanghui_index)
print (embed_kanghui)

tensor([ 0.2476,  0.8029, -0.8743, -0.5926, -1.0005,  0.0818,  0.7871,  1.2519],
       grad_fn=<EmbeddingBackward>)


In [20]:
all_index = torch.tensor([w for w in range(5)], dtype = torch.long)

all_words_embed = embeddings(all_index)
print (all_index)
print(all_words_embed)

tensor([0, 1, 2, 3, 4])
tensor([[ 0.2476,  0.8029, -0.8743, -0.5926, -1.0005,  0.0818,  0.7871,  1.2519],
        [-0.0497,  0.8289, -1.3579,  0.7531, -0.3492, -0.7852,  0.7412, -1.2337],
        [ 0.9984, -0.2338,  1.0809, -0.5303,  0.5613,  0.9074, -0.6958,  0.1478],
        [ 0.0069,  1.2749, -1.2883, -2.0458,  0.5173, -0.6142,  1.2101, -1.7319],
        [ 0.2583,  0.2048,  0.1291, -0.6999, -0.3557, -0.1726,  0.1691, -0.7118]],
       grad_fn=<EmbeddingBackward>)
